import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/shared/navbar";
import { LanguageProvider } from "@/components/context/language-context";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="uz" suppressHydrationWarning>
            <body>
                <LanguageProvider>
                    <ThemeProvider attribute="class" defaultTheme="system">
                        <Navbar />
                        <main className="pt-24"> {children}</main>
                    </ThemeProvider>
                </LanguageProvider>
            </body>
        </html>
    );
}
